### ISSUE TITLE
Юзабилити: отображение расходов и поступлений

### ISSUE THREAD

**Issue by jekhor** [jekhor/MVOfund#4]
Определиться с вариантом показа расходов и поступлений: смешивать их в одной табличке, как сейчас, или же делать раздельные таблички ("вкладки" или иное разделение).

**Comment by davojta** [comment]
можно сделать разделением по цвету - поступления - зеленые, расходы - красные
поступления еще могут быть просто черные

**Comment by jekhor** [comment]
Разделение по цвету есть. Проблема в том, что поступлений очень много, а
расходов мало.

17 Дек 2016 г. 11:47 пользователь "Dzianis Sheka" <notifications@github.com>
написал:

**Comment by davojta** [comment]
Из вариантов - 
1) простой - сделать поступления маленьким шрифтом
2) средний по сложности - схлопывать много маленьких
3) относительно простой - сделать табы

Но я бы скорее задался вопросом кто вообще сюда будет смотреть + прикрутил аналитку, провел опрос у потенциальных пользователей

**Comment by jekhor** [comment]
Я пока склоняюсь к табам, потому что количество поступлений и расходов отличается на порядок-два.
Городить что-то сложное смысла нет, именно потому, что не сильно часто будут смотреть. Но более-менее удобное представление надо иметь.
