### ISSUE TITLE
Определиться с доменом

### ISSUE THREAD

**Issue by jekhor** [jekhor/MVOfund#7]
Сейчас сервис использует домен fund.minsk.bike, это может вызвать некоторые вопросы из-за того, что не в белорусской зоне. Подумать, является ли это проблемой, и не надо ли выбрать другой домен.

**Comment by davojta** [comment]
я думаю пока проблемы нет оставить как есть
если будут намечаться проблемы - сделать по нормальном в бел зоне
то, что я слышал - касалось интернет магазинов

**Comment by jekhor** [comment]
Пока что завели на fund.bike.org.by, но работает и на fund.minsk.bike
